#!/usr/bin/env node
/**
 * apa drop-in: make this kit usable from a host project (Claude Code / Codex) with ZERO install.
 *
 * Run from your TARGET project root (a codebase or a research-article folder), or pass --project <dir>.
 * It writes ONE idempotent APA pointer block into the project's CLAUDE.md AND AGENTS.md so the agent
 * self-orients on a plain-English ask. The CLIs are pure `node` (zero deps), so they work the moment this
 * folder exists - no install. It does NOT register host skills, scaffold a matter, sign, or file.
 *
 *   cd <your-project> && node <path-to-kit>/scripts/dropin.mjs
 *   node scripts/dropin.mjs --project /path/to/your-project
 *
 * Re-run any time (e.g. after moving the kit): the block is delimited by markers and updated in place,
 * never duplicated. Node >=18, ESM, zero dependencies.
 */

import { readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, resolve } from "node:path";

// scripts/dropin.mjs -> kit root is one level up.
export const KIT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const START = "<!-- APA:DROPIN:START (generated by apa scripts/dropin.mjs - re-run to refresh, do not hand-edit inside) -->";
export const END = "<!-- APA:DROPIN:END -->";

/** Forward slashes so the doc path is portable (node accepts them on Windows too). */
function fwd(p) { return String(p).split("\\").join("/"); }

/** The agent-facing pointer block. `relKit` is the kit path relative to the project root. */
export function pointerBlock(relKit) {
  const k = fwd(relKit) || ".";
  return [
    START,
    "## Patent prep — Agent-Native-Patent-Artifact (APA) toolkit",
    "",
    `This project includes the APA patent toolkit at \`${k}/\`. When the user asks to capture an invention`,
    "disclosure, search prior art, draft claims / specification / figures, analyze patentability, run a rigor",
    "review, or assemble a USPTO filing package, USE IT — do not improvise patent procedure.",
    "",
    "**How to use (zero-install):**",
    `- Skills (the procedure specs): read \`${k}/skills/<name>/SKILL.md\` and follow it. Available skills:`,
    "  `disclosure-capture`, `compiler`, `prior-art-search`, `claim-drafting`, `specification-drafting`,",
    "  `figure-generation`, `patentability-analysis`, `rigor-review`, `examiner-adversary`, `filing-assembly`,",
    "  `office-action`, and `autoprep` (chains the whole lifecycle with the gates + human checkpoints).",
    `- CLIs (deterministic, pure \`node\`, zero deps): e.g.`,
    `  \`node ${k}/packages/apa-validate/validate.mjs <matter>\` (Level-1 mechanical check),`,
    `  \`node ${k}/packages/apa-assemble/cli.mjs --matter <matter>\` (pre-filing go/no-go). The full ordered`,
    `  command-by-command walkthrough is \`${k}/docs/walkthrough.md\`.`,
    "- A \"matter\" is a directory (`PATENT.md` + `logic/ src/ trace/ evidence/`). Create it in THIS project",
    "  (e.g. `./patent/`) and keep it gitignored — an unfiled disclosure is a confidential 102 / trade-secret",
    "  asset. The skills scaffold it; you do not hand-author it.",
    "",
    "**Non-negotiable guardrails (never weaken):** never sign, file, name an AI as inventor, generate a",
    "pre-executed declaration, or assert micro-entity status. Every external send is byte-scanned",
    "(`apa-redact`); HIGH-sensitivity content blocks egress. The validator asserts only MECHANICAL facts —",
    `§112 sufficiency and 101/102/103 are FLAGS for a human practitioner, never a clearance or legal opinion.`,
    `Full text: \`${k}/docs/legal-guardrails.md\`.`,
    "",
    "To start, the user can simply say e.g. *\"use the APA toolkit to capture a disclosure for my invention\"*",
    "or *\"run autoprep for this idea\"*.",
    END,
  ].join("\n");
}

/** Insert/refresh the marked block in `file`. Returns 'created'|'appended'|'updated'|'unchanged'. */
export function upsertBlock(file, block) {
  const cur = existsSync(file) ? readFileSync(file, "utf8") : "";
  const s = cur.indexOf(START);
  if (s !== -1) {
    const e = cur.indexOf(END);
    if (e === -1) throw new Error(`${file} has an APA start marker but no end marker; remove the stray marker and re-run.`);
    const next = cur.slice(0, s) + block + cur.slice(e + END.length);
    if (next === cur) return "unchanged";
    writeFileSync(file, next);
    return "updated";
  }
  if (cur === "") { writeFileSync(file, block + "\n"); return "created"; }
  const sep = cur.endsWith("\n") ? "\n" : "\n\n";
  writeFileSync(file, cur + sep + block + "\n");
  return "appended";
}

/** Wire the pointer into a project dir. Returns { rel, results: [{file,status}] }. */
export function dropin(projectDir) {
  const project = resolve(projectDir);
  if (!existsSync(project) || !statSync(project).isDirectory()) {
    throw new Error(`project dir not found: ${project}`);
  }
  if (project === KIT_ROOT) {
    throw new Error("--project is the kit itself; run this from your TARGET project (the codebase or article folder), not inside the kit.");
  }
  const rel = relative(project, KIT_ROOT) || ".";
  const block = pointerBlock(rel);
  const results = [];
  for (const name of ["CLAUDE.md", "AGENTS.md"]) {
    results.push({ file: name, status: upsertBlock(join(project, name), block) });
  }
  return { rel: fwd(rel), results };
}

function main() {
  const argv = process.argv.slice(2);
  let project = process.cwd();
  for (let i = 0; i < argv.length; i++) if (argv[i] === "--project") project = argv[++i] || ".";
  let out;
  try { out = dropin(project); }
  catch (e) { process.stderr.write(`error: ${e && e.message ? e.message : e}\n`); process.exit(2); }
  process.stdout.write(`APA drop-in wired into ${resolve(project)}\n`);
  process.stdout.write(`  kit at (relative): ${out.rel}\n`);
  out.results.forEach((r) => process.stdout.write(`  ${r.file}: ${r.status}\n`));
  process.stdout.write("\nNext: open this project in Claude Code or Codex and say e.g.\n");
  process.stdout.write("  \"use the APA toolkit to capture a disclosure for my invention\"\n");
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) main();
